#pragma once

#ifndef OSCI_FILE_IMPORT_ENABLE_GPLA
#define OSCI_FILE_IMPORT_ENABLE_GPLA 1
#endif

#ifndef OSCI_FILE_IMPORT_ENABLE_SVG
#define OSCI_FILE_IMPORT_ENABLE_SVG 1
#endif

#ifndef OSCI_FILE_IMPORT_ENABLE_TXT
#define OSCI_FILE_IMPORT_ENABLE_TXT 1
#endif
